### PR TITLE
New Lineages Update: 7 new lineages active through 2022-12-01

### PR DESCRIPTION
**Pull request by jmcbroome**
| Lineage Name     | Parent Lineage   |   Initial Size | Earliest Appearance   | Last Checked   |   Latest Size | Initially Circulating In                                                              | Associated Changes           | View On Cov-Spectrum                                                                                                                                                                                    | View On Taxonium (Public Samples Only)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|:-----------------|:-----------------|---------------:|:----------------------|:---------------|--------------:|:--------------------------------------------------------------------------------------|:-----------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| auto.XBB.1.4.0   | XBB.1.4          |             32 | 2022-10-10            | 2022-12-01     |           115 | Denmark,Norway,Sweden,Austria,Iceland,Israel                                          | >S:S673G                     | [View On Cov-Spectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3AXBB.1.4%2A%26%5B3-of%3A26160C%2C+2164A%2C+23579G%5D)                    | [View On Taxonium (Public Samples Only)](https://taxonium.org/?backend=https://api.cov2tree.org&srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22XBB.1.4%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%22ab0%22%2C%22type%22%3A%22meta_pango_lineage_usher%22%2C%22method%22%3A%22text_exact%22%2C%22text%22%3A%22XBB.1.4%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%221ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2226160%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%222ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%222164%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%223ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2223579%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%5D%2C%22boolean_method%22%3A%22and%22%7D%5D&enabled=%7B%22aa1%22%3A%22true%22%7D&zoomToSearch=0)                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| auto.BN.1.3      | BN.1             |             39 | 2022-10-11            | 2022-12-01     |            75 | Denmark,Canada,Austria,USA                                                            | ORF1ab:F3753L,ORF1ab:H4831Y> | [View On Cov-Spectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABN.1%2A%26%5B3-of%3A19839C%2C+14755T%2C+11522C%5D)                      | [View On Taxonium (Public Samples Only)](https://taxonium.org/?backend=https://api.cov2tree.org&srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22BN.1%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%22ab0%22%2C%22type%22%3A%22meta_pango_lineage_usher%22%2C%22method%22%3A%22text_exact%22%2C%22text%22%3A%22BN.1%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%221ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2211522%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%222ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2214755%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%223ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2219839%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%5D%2C%22boolean_method%22%3A%22and%22%7D%5D&enabled=%7B%22aa1%22%3A%22true%22%7D&zoomToSearch=0)                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| auto.BQ.1.2.3    | BQ.1.2           |             45 | 2022-09-07            | 2022-12-01     |            78 | Mongolia,Turkey,USA,Japan,Israel,Netherlands,SouthKorea,England,Denmark,Germany,Spain | N:H300N>ORF1ab:P5828S>       | [View On Cov-Spectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABQ.1.2%2A%26%5B5-of%3A17746T%2C+4414G%2C+29171A%2C+27513T%2C+15960A%5D) | [View On Taxonium (Public Samples Only)](https://taxonium.org/?backend=https://api.cov2tree.org&srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22BQ.1.2%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%22ab0%22%2C%22type%22%3A%22meta_pango_lineage_usher%22%2C%22method%22%3A%22text_exact%22%2C%22text%22%3A%22BQ.1.2%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%221ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2215960%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%222ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227513%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%223ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2229171%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%224ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2217746%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%225ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%224414%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%5D%2C%22boolean_method%22%3A%22and%22%7D%5D&enabled=%7B%22aa1%22%3A%22true%22%7D&zoomToSearch=0) |
| auto.BQ.1.13.2   | BQ.1.13          |             38 | 2022-10-10            | 2022-12-01     |            68 | USA,Netherlands,England,Israel,Iceland,Australia,Canada                               | >S:F157L>                    | [View On Cov-Spectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABQ.1.13%2A%26%5B4-of%3A7318T%2C+22033A%2C+19266C%2C+26106C%5D)          | [View On Taxonium (Public Samples Only)](https://taxonium.org/?backend=https://api.cov2tree.org&srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22BQ.1.13%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%22ab0%22%2C%22type%22%3A%22meta_pango_lineage_usher%22%2C%22method%22%3A%22text_exact%22%2C%22text%22%3A%22BQ.1.13%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%221ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%227318%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%222ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2222033%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%223ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2219266%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%224ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2226106%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%5D%2C%22boolean_method%22%3A%22and%22%7D%5D&enabled=%7B%22aa1%22%3A%22true%22%7D&zoomToSearch=0)                                                                                                                                                                                                                           |
| auto.BQ.1.23.2   | BQ.1.23          |             28 | 2022-10-15            | 2022-12-01     |            43 | Australia,Singapore,USA                                                               | >>ORF1ab:D1939G              | [View On Cov-Spectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABQ.1.23%2A%26%5B3-of%3A4144A%2C+6081G%2C+22591T%5D)                     | [View On Taxonium (Public Samples Only)](https://taxonium.org/?backend=https://api.cov2tree.org&srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22BQ.1.23%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%22ab0%22%2C%22type%22%3A%22meta_pango_lineage_usher%22%2C%22method%22%3A%22text_exact%22%2C%22text%22%3A%22BQ.1.23%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%221ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2222591%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%222ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%224144%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%223ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%226081%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%5D%2C%22boolean_method%22%3A%22and%22%7D%5D&enabled=%7B%22aa1%22%3A%22true%22%7D&zoomToSearch=0)                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| auto.BQ.1.1.4.3  | BQ.1.1.4         |             20 | 2022-10-18            | 2022-12-01     |            79 | Denmark,Croatia,Australia,Israel,USA,Sweden                                           | ORF1ab:T1168A>               | [View On Cov-Spectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABQ.1.1.4%2A%26%5B2-of%3A28657T%2C+3767G%5D)                             | [View On Taxonium (Public Samples Only)](https://taxonium.org/?backend=https://api.cov2tree.org&srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22BQ.1.1.4%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%22ab0%22%2C%22type%22%3A%22meta_pango_lineage_usher%22%2C%22method%22%3A%22text_exact%22%2C%22text%22%3A%22BQ.1.1.4%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%221ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%223767%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%222ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2228657%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%5D%2C%22boolean_method%22%3A%22and%22%7D%5D&enabled=%7B%22aa1%22%3A%22true%22%7D&zoomToSearch=0)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| auto.BQ.1.1.20.1 | BQ.1.1.20        |             53 | 2022-10-24            | 2022-12-01     |            90 | Denmark                                                                               | S:A1070V                     | [View On Cov-Spectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABQ.1.1.20%2A%26%5B1-of%3A24771T%5D)                                     | [View On Taxonium (Public Samples Only)](https://taxonium.org/?backend=https://api.cov2tree.org&srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22BQ.1.1.20%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%22ab0%22%2C%22type%22%3A%22meta_pango_lineage_usher%22%2C%22method%22%3A%22text_exact%22%2C%22text%22%3A%22BQ.1.1.20%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%221ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2224771%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%5D%2C%22boolean_method%22%3A%22and%22%7D%5D&enabled=%7B%22aa1%22%3A%22true%22%7D&zoomToSearch=0)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |

### CODE REVIEW

**Comment by AngieHinrichs** [comment]
* auto.XBB.1.4.0 has been designated XBB.1.4.1
* autoBQ.1.13.2 has been proposed: https://github.com/cov-lineages/pango-designation/issues/1400
* The others look reasonable.
* autoBQ.1.23.2 says size 43 but the branch with ORF1ab:D1939G has only 30 sequences in the 2022-12-09 tree... can you send me a list of the 43?

Are parameters listed somewhere?  I'm curious what cutoff led to 7 proposals (as opposed to 10, 20, 1000 🙂)

**Comment by jmcbroome** [comment]
Thank you for looking at this in detail Angie! I'm very happy to hear that some of the automated lineages were already proposed- suggests we're going in the right direction! 

Re: parameters used- There are different groups of parameters- for initial designation, there's all the parameters I've laid out in the past on the prototype repo. There are a few more parameters for controlling the selection of automated lineages for formal review that are simpler- including minimum percentage growth over time, flat minimum total growth in samples from initial designation, and total number of weeks actively circulating.

I was really aggressive about filtering down this PR. I set a minimum weekly percentage growth increase of 50% with a minimum of 5 samples total gained and at least 1 total week of active circulating and sampling. If I reduce that growth threshold to something more reasonable, like 10%, I actually get 121 proposals. But I wanted this to be a small, high quality, easy to review set. 

I'll also note that I was having some issues with odd inconsistencies in lineage sizes over time and how they were computed in some cases that I still need to clean up. There's also an argument I should use mean instead of minimum to smooth out some of those issues but in those cases I did have problems with one week of huge relative growth then a sudden cessation looking more relevant than it maybe is. One of the critical questions that will inform this paramter is how many lineages do we actually want to review and incorporate each week. 121 lineages is unwieldly and also too much text for the pull request body!

Re: the XBB sublineage- do you mean it was already designated before this proposal, or that you took this proposal and went ahead and made the designation? I did write code to block proposals that match existing designations, of course, and overwrite automated lineage proposals that got independently formally designated in any given week with the formal designation, but it might not have worked in that case.

Re: the 43 sample lineage- sent you a file on slack! There are some explanations for why a lineage might shrink, being either tree topology shifts as it's optimized and new data flows in, or the formal designation of a new lineage somewhere in the descendents of the automated proposal.

**Comment by AngieHinrichs** [comment]
Thanks!  Sustained 50% growth per week is pretty impressive.  But yeah, it is nice to have a small test set to review, and 121 would be too many.  I wonder how much curator time we can expect per week.  I think it would be good to have maybe ~15-20? per week, but expecting some weeks to have more and some less depending on what's going on with spread and with genome sequence uploading (there are some countries that upload pretty infrequently, and then all of a sudden you get a couple months of new history from them).

XBB.1.4.1 was already designated before your proposal ([on Nov. 25 from #1352](https://github.com/cov-lineages/pango-designation/issues/1352#issuecomment-1327692890)).  It was annotated on the tree starting with the 2022-11-28 build.

Thanks for sending the sample names.  They appear to be from a different branch!  Here's a taxonium view of the 2022-11-29 tree, with red circles around the 43 samples in the list that you sent -- but pink samples down below on the branch with ORF1ab:D1939G (samples colored by allele at ORF1ab:1939) which is what I think was intended:
image
Zooming in on the pink (ORF1ab:D1939G) samples, they look like your lineage description ("Australia,Singapore,USA"):
image
-- while the list of 43 names has many more countries and only 2 sequences from Australia.

Venturing a guess, perhaps a node_# from one tree was used to look up samples from a slightly different tree??  (It's probably something else but I always have to guess 😆)

**Comment by jmcbroome** [comment]
Thanks for the comments Angie- we already talked on slack but I'm putting out the answer to the auto.BQ.1.23.2 here as well for the record!

It's a case of name collision. On 11-24, the designation code created a new lineage with ORF1ab:D1939G and named it auto.BQ.1.23.2. On 12-01, this lineage failed to transfer to the new tree, leaving the name unused. A brand new lineage was designated nearby, and assigned the name... auto.BQ.1.23.2. 

When I compiled my reports, paths and countries were reported from the oldest report (initial designation), while final sizes were obtained via matUtils from the latest tree where it was present. Therefore the path/mutation match the original auto.BQ.1.23.2 and the size matches the new auto.BQ.1.23.2. 

This is definitely a bug, and I need to figure out some way to effectively transfer lineages between trees- or avoid having to transfer them altogether- and also track issues like dropped and reused names when I'm compiling reports for lineage proposals.

**Pull request closed without merging**
